---

- hosts: localhost
  tasks:
    - name: demo
      shell: 
        cmd: echo Testing
      register: result 

    - name: debug
      debug:
        var: result['cmd']

    - name: Create Dir
      file:
        path: /tmp/somedir
        state: directory
      when: " result['cmd'].find('Testing')"
